from collections import OrderedDict
from threading import RLock
from typing import Iterable, Literal
from pydantic import BaseModel
from fastembed import TextEmbedding
from loguru import logger
from app.config import settings
from app.services.custom_models import register_custom_models

InputType = Literal["passage", "query"]
DefaultInputType = Literal["passage", "query", "auto"]
SUPPORTED_INPUT_TYPES: set[str] = {"passage", "query"}
SUPPORTED_DEFAULT_INPUT_TYPES: set[str] = {*SUPPORTED_INPUT_TYPES, "auto"}
QUERY_HINTS = {
    "где",
    "как",
    "когда",
    "кто",
    "куда",
    "зачем",
    "почему",
    "сколько",
    "что",
    "чем",
    "какой",
    "какая",
    "какое",
    "какие",
    "найди",
    "покажи",
    "расскажи",
    "объясни",
    "дай",
    "де",
    "як",
    "коли",
    "хто",
    "куди",
    "навіщо",
    "чому",
    "скільки",
    "що",
    "чим",
    "який",
    "яка",
    "яке",
    "які",
    "знайди",
    "покажи",
    "розкажи",
    "поясни",
    "дай",
    "where",
    "how",
    "when",
    "who",
    "why",
    "what",
    "which",
    "find",
    "show",
    "explain",
    "tell",
    "give",
}

register_custom_models()

model_cache: OrderedDict[str, TextEmbedding] = OrderedDict()
model_cache_lock = RLock()


def _evict_lru_models_if_needed() -> None:
    cache_limit = max(1, settings.MODEL_CACHE_LIMIT)
    while len(model_cache) > cache_limit:
        evicted_model_id, _ = model_cache.popitem(last=False)
        logger.info(
            f"Evicting least recently used embedding model from memory: {evicted_model_id}"
        )


def get_model(model_id: str) -> TextEmbedding:
    """Fetch the model from cache, or load it if not present."""

    with model_cache_lock:
        cached_model = model_cache.get(model_id)
        if cached_model is not None:
            model_cache.move_to_end(model_id)
            return cached_model

        logger.info(f"Loading embedding model into memory: {model_id}")

        # Configure providers based on GPU setting
        providers = None
        if settings.USE_GPU:
            providers = ["CUDAExecutionProvider"]
            logger.info("GPU acceleration (CUDAExecutionProvider) enabled.")

        model = TextEmbedding(
            model_id, threads=settings.EMBEDDING_THREADS, providers=providers
        )

        resolved_providers = model.model.model.get_providers()
        logger.info(
            f"Model {model_id} loaded successfully with providers: {resolved_providers}"
        )

        model_cache[model_id] = model
        _evict_lru_models_if_needed()
        return model


def preload_default_model():
    """Hook to pre-load the default model during startup."""
    logger.info("Preloading default embedding model...")
    get_model(settings.DEFAULT_EMBEDDING_MODEL)
    logger.info(
        f"Default embedding model {settings.DEFAULT_EMBEDDING_MODEL} preloaded successfully."
    )


class EmbeddingResult(BaseModel):
    vectors: list[list[float]]
    """Vectors generated by the model"""
    prompt_tokens: int
    """Token usage count for the input text"""
    model_used: str
    """Model used to generate the embeddings"""


def resolve_model_request(
    requested_model: str, requested_input_type: InputType | None = None
) -> tuple[str, InputType | None]:
    """Resolve optional model suffix aliases like model:query or model:passage."""

    model_id = requested_model
    input_type = requested_input_type

    for separator in (":", "#"):
        if separator not in requested_model:
            continue
        maybe_model, maybe_input_type = requested_model.rsplit(separator, 1)
        if maybe_input_type in SUPPORTED_INPUT_TYPES:
            model_id = maybe_model
            input_type = maybe_input_type
            break

    if input_type is None:
        default_input_type = _default_input_type()
        input_type = None if default_input_type == "auto" else default_input_type

    if input_type is not None and input_type not in SUPPORTED_INPUT_TYPES:
        raise ValueError(
            f"Invalid input_type '{input_type}'. Expected one of {sorted(SUPPORTED_INPUT_TYPES)}"
        )

    return model_id, input_type


def _default_input_type() -> DefaultInputType:
    default_input_type = settings.DEFAULT_INPUT_TYPE
    if default_input_type not in SUPPORTED_DEFAULT_INPUT_TYPES:
        raise ValueError(
            f"Invalid DEFAULT_INPUT_TYPE '{default_input_type}'. "
            f"Expected one of {sorted(SUPPORTED_DEFAULT_INPUT_TYPES)}"
        )
    return default_input_type


def _effective_input_type(input_type: InputType | None) -> InputType | None:
    if input_type is not None:
        return input_type
    default_input_type = _default_input_type()
    return None if default_input_type == "auto" else default_input_type


def _is_e5_model(model_id: str) -> bool:
    return "e5" in model_id.lower()


def _looks_like_query(text: str) -> bool:
    stripped = text.strip()
    if not stripped:
        return False
    if stripped.endswith("?"):
        return True

    first_word = stripped.split(maxsplit=1)[0].lower().strip("¿?!.,:;\"'()[]{}")
    if first_word in QUERY_HINTS:
        return True

    return False


def _resolve_text_input_type(text: str, input_type: InputType | None) -> InputType:
    if input_type is not None:
        return input_type
    return "query" if _looks_like_query(text) else "passage"


def _apply_e5_prefix(text: str, input_type: InputType | None) -> str:
    stripped = text.lstrip()
    if stripped.startswith("query:") or stripped.startswith("passage:"):
        return text
    return f"{_resolve_text_input_type(text, input_type)}: {text}"


def _prepare_texts(
    texts: Iterable[str] | str, model_id: str, input_type: InputType | None
) -> Iterable[str] | str:
    if isinstance(texts, str):
        return _apply_e5_prefix(texts, input_type) if _is_e5_model(model_id) else texts

    if _is_e5_model(model_id):
        return [_apply_e5_prefix(text, input_type) for text in texts]

    return texts


def embed_text(
    texts: Iterable[str] | str,
    model_id: str = settings.DEFAULT_EMBEDDING_MODEL,
    input_type: InputType | None = None,
) -> EmbeddingResult:
    try:
        model = get_model(model_id)
    except Exception as e:
        logger.error(f"Error initializing embedding model: {e}")
        raise

    try:
        prepared_texts = _prepare_texts(
            texts, model_id, _effective_input_type(input_type)
        )

        # model.embed natively batches an iterable of documents giving an iterable of numpy arrays
        vectors = [
            vec.tolist()
            for vec in model.embed(prepared_texts, batch_size=settings.BATCH_SIZE)
        ]

        # token_count returns a single int for total tokens
        total_tokens = model.token_count(prepared_texts)

        return EmbeddingResult(
            vectors=vectors, prompt_tokens=total_tokens, model_used=model_id
        )
    except Exception as e:
        logger.error(f"Error generating embeddings: {e}")
        raise
