from pydantic import BaseModel
from typing import List, Literal


class Embedding(BaseModel):
    """Represents an embedding vector returned by embedding endpoint."""

    embedding: List[float]
    """The embedding vector, which is a list of floats.

    The length of vector depends on the model as listed in the /v1/models endpoint.
    """

    index: int
    """The index of the embedding in the list of embeddings."""

    object: Literal["embedding"]
    """The object type, which is always "embedding"."""


class Usage(BaseModel):
    """The usage information for the request."""

    prompt_tokens: int
    """The number of tokens used by the prompt."""

    total_tokens: int
    """The total number of tokens used by the request."""


class CreateEmbeddingResponse(BaseModel):
    data: List[Embedding]
    """The list of embeddings generated by the model."""

    model: str
    """The name of the model used to generate the embedding."""

    object: Literal["list"]
    """The object type, which is always "list"."""

    usage: Usage
    """The usage information for the request."""
